from enum import Enum

class Tag(Enum):
    """
    微信公众号所带标签的枚举类，用于存储理想的tags。
    """
    BEV = "BEV"
    TRANSFORMER = "Transformer"
    BEV_TRANSFORMER = "BEV+Transformer"
    END_TO_END = "端到端"
    LARGE_MODEL = "大模型"
    GPT = "GPT"
    AUTO_DRIVING = "自动驾驶"
    SMART_DRIVING = "智能驾驶"
    FSD = "FSD"
    NOA = "NOA"
    DRIVING = "行车"
    PARKING = "泊车"
    SMART_CAR = "智能汽车"
    TESLA = "特斯拉"
    HORIZON = "地平线"
    LIDAR = "激光雷达"
    AI_CHIP = "AI芯片"
    DEEP_LEARNING = "深度学习"
    COMPUTER_VISION = "计算机视觉"
    AUTONOMOUS_VEHICLES = "自动驾驶车辆"
    SENSOR_TECHNOLOGY = "传感器技术"